#!/usr/bin/env bash
# A Bash script that pings 5 times an IP address passed as an argument.
if [ -z "$1" ]; then
  echo "Usage: 5-is_the_host_on_the_network {IP_ADDRESS}"
  exit 1
fi

ip_address="$1"

ping -c 5 "$ip_address"
